version: '2'
services:
  sygi-app:
    image: sygi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sygi-postgresql:5432/sygi
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://sygi-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://sygi-elasticsearch:9200
    ports:
      - 8080:8080
  sygi-postgresql:
    extends:
      file: postgresql.yml
      service: sygi-postgresql
  sygi-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: sygi-elasticsearch
